### ISSUE TITLE
Chybí číslování u některých kapitol

### ISSUE THREAD

**Issue by JanHubeny1** [Codeventure-cz/dokumentace#1]
Čest práci, soudruhu,
chybí číslování u kapitol jako např. Literatura, Seznam obrázku atp. (vycházím ze SOČ šablony ve Wordu [zde](https://www.soc.cz/dokumenty/sablona_SOC.docx), kde to takto je)
Díky, GL

**Comment by hansslim** [comment]
dej do main.tex před \begin{document} toto:
```
\patchcmd{\thebibliography}{*}{}{}{} %% přidání číslování pro nadpis zdrojů
\patchcmd{\listoffigures}{*}{}{}{} %% přidání číslování pro nadpis seznamu obrázků
\patchcmd{\listoftables}{*}{}{}{} %% přidání číslování pro nadpis seznamu tabulek
```
